//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace carNews
{
    public partial class news1
    {
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblViews;
        protected global::System.Web.UI.WebControls.Image imgArticle;
        protected global::System.Web.UI.WebControls.HyperLink hlBack;
        protected global::System.Web.UI.WebControls.HyperLink hlNext;
        protected global::System.Web.UI.WebControls.Label lblTag1;
        protected global::System.Web.UI.WebControls.Label lblTag2;
        protected global::System.Web.UI.WebControls.Label lblTag3;
        protected global::System.Web.UI.WebControls.Label lblTag4;
        protected global::System.Web.UI.WebControls.Label lblTag5;
        protected global::System.Web.UI.WebControls.Image imgSide1;
        protected global::System.Web.UI.WebControls.Image imgSide2;
    }
}
