//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace carNews
{
    public partial class news2
    {
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblViews;
        protected global::System.Web.UI.WebControls.Image imgArticle;
        protected global::System.Web.UI.WebControls.HyperLink hlBack;
        protected global::System.Web.UI.WebControls.HyperLink hlPrev;
        protected global::System.Web.UI.WebControls.Image imgSide1;
        protected global::System.Web.UI.WebControls.Image imgSide2;
    }
}
